[project]
name = "labs"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "pytest>=9.0.1",
    "rich>=14.2.0",
]
[[tool.mypy.overrides]]
module = ["rich.*"]
ignore_missing_imports = true
